### ISSUE TITLE
Popup starts as closed

### ISSUE THREAD

**Issue by 0xTimepunk** [tasoskakour/react-use-oauth2#3] opened 2022-06-20 16:49 UTC
Hey!

I just followed your guidelines for implementing this, specifically for Twitter Oauth2 in a react 18 typescript app.

Whenever I launch the popup by pressing login, I receive a console warn saying 'Warning: Popup was closed before completing authentication.' Upon inspecting the popupRef it's as if it becomes undefined immediately after opening the popup. After completing the authentication with the callback, the popup never closes, because it's already set as 'closed'.

I can upload a repo to showcase this to you if needed.

thanks

**Comment by 0xTimepunk** [comment] 2022-06-20 16:57
Note: upon inspecting the browser console of the popup window, the following error appears, indicating that window.opener is not defined.
'react-dom.development.js:22839 Uncaught Error: No window opener'

**Comment by tasoskakour** [comment] 2022-06-21 09:54
Hey @0xTimepunk thanks for reporting this.

Could you please post your Browser specs?

Also a showcase of this could help a lot.

**Comment by 0xTimepunk** [comment] 2022-06-22 09:19
@tasoskakour I just invited you to a private repo to showcase the test with twitter oauth.

This test was ran in a Mac M1 ih firefox 101.0.1 and chrome 103.0.5060.53  (arm build, with ad block disabled).

Do also note that the twitter oauth2 is not working properly because I believe something is missing in the url, such as `code_challenge_method=s256, and the callback url not being formatted properly `http%3A%2F%2F127.0.0.1%3A3000%2Fcallback`

I noticed by copying the source files directly and tweaking the setTimeout timer to a higher number and generating the twitter url using `twitter-api-sdk`npm package helps me proceed to the callback moment, but issues still lie with window.opener. A solution I am trying to employ is to store the `code` in localStorage temporarily and send it to my backend for token exchange.

**Comment by tasoskakour** [comment] 2022-06-23 15:25
@0xTimepunk 

After some digging this is a known issue with Twitter OAuth2: https://twittercommunity.com/t/oauth2-authorization-via-window-open/167249 (but not with OAuth1).

It  looks like that when redirecting to `https://twitter.com/i/oauth2/authorize` Twitter adds **Cross-Origin-Opener-Policy** header which makes `window.opener` lose all useful data. As a result the `popupRef.current.window` is null so it assumes that the popup has beem closed: https://github.com/tasoskakour/react-use-oauth2/blob/4fdad3e8602dcf8e97de560c2802d1359d9da834/src/components/use-oauth2.ts#L212

Feel free to open a PR that will detect if the *Cross-Origin-Opener-Policy* is present or if the *window.opener* is null so that the code can catch this scenario 🙂

**Comment by avilao** [comment] 2022-10-09 23:41
Hi all. Did you manage to solve this? I'm having the same challenge with a different provider.

**Comment by Shaavin** [comment] 2023-01-02 01:01
I am experiencing a similar issue, but with Google. Everything appears to be configured properly, but the windows force closes before a user is able to complete the authentication process. Any thoughts on this one?

**Comment by tasoskakour** [comment] 2023-01-02 08:09
@Shaavin I cannot reproduce the error. Could you provide a sample sandbox please?

**Comment by tasoskakour** [comment] 2023-01-04 06:25
@Shaavin @avilao Fixed in https://github.com/tasoskakour/react-use-oauth2/pull/9 
Could you try again with `v1.0.14`?

**Closed** 2023-04-21 14:45 UTC

**Comment by tiagoefreitas** [comment] 2023-10-02 14:02
I am trying this in a nextjs app for a zapier nla oauth and I get this after redirect:

Uncaught Error: No window opener
    at eval (index.js:1:2789)
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
    at commitPassiveMountEffects_begin (react-dom.development.js:24878:1)
    at commitPassiveMountEffects (react-dom.development.js:24866:1)
    at flushPassiveEffectsImpl (react-dom.development.js:27039:1)
    at flushPassiveEffects (react-dom.development.js:26984:1)
    at eval (react-dom.development.js:26769:1)
    at workLoop (scheduler.development.js:266:1)
    at flushWork (scheduler.development.js:239:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:1)
eval @ index.js:1
commitHookEffectListMount @ react-dom.development.js:23150
commitPassiveMountOnFiber @ react-dom.development.js:24926
commitPassiveMountEffects_complete @ react-dom.development.js:24891
commitPassiveMountEffects_begin @ react-dom.development.js:24878
commitPassiveMountEffects @ react-dom.development.js:24866
flushPassiveEffectsImpl @ react-dom.development.js:27039
flushPassiveEffects @ react-dom.development.js:26984
eval @ react-dom.development.js:26769
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
client.js:1 The above error occurred in the <g> component:

    at g (webpack-internal:///./node_modules/@tasoskakour/react-use-oauth2/dist/esm/index.js:9:2269)
    at ZapierCallback
    at App (webpack-internal:///./node_modules/next/dist/pages/_app.js:24:1)
    at PathnameContextProviderAdapter (webpack-internal:///./node_modules/next/dist/shared/lib/router/adapters.js:79:11)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:5389)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:2:7785)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:78:1)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:182:11)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:396:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
